version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
